[tasks.format]
install_crate = "rustfmt"
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["lambda", "build", "--release"]
dependencies = ["format"]

[tasks.run]
command = "cargo"
args = ["run"]
dependencies = ["format"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.staging]
command = "cargo"
args = [
    "lambda",
    "deploy",
    "--lambda-dir",
    "../../target/lambda/",
    "--binary-name",
    "document-indexer",
    "--region",
    "us-east-2",
    "--iam-role",
    "{{IAM_ROLE}}",
    "--profile",
    "app",
    "document-indexer-stage",
]
dependencies = ["build", "format"]

[tasks.production]
command = "cargo"
args = [
    "lambda",
    "deploy",
    "--lambda-dir",
    "../../target/lambda/",
    "--region",
    "us-east-2",
    "--iam-role",
    "{{IAM_ROLE}}",
    "--profile",
    "app",
    "document-indexer",
]
dependencies = ["clean", "build", "format"]
